site_name: mappertec
repo_url: https://github.com/mappertec/mappertec
repo_name: mappertec/mappertec
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: black
  features:
    - navigation.tabs
    - content.code.copy
    - content.code.link
plugins:
  - blog
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Blog:
      - blog/index.md
